language: node_js
node_js:
  - 12
sudo: required
services:
  - docker

before_install:
  - npm i -g npm@latest
  - docker build -t ricardo77/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ricardo77/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-935510226691"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
